Greeting.create(message: "Hello, world!")
Greeting.create(message: "Hi there!")
Greeting.create(message: "Good day!")
Greeting.create(message: "Greetings!")
Greeting.create(message: "Hey, how's it going?")
